FROM postgres:16

# Set up the database initialization script
RUN apt-get update && apt-get install \
    python3 python3-venv -y \
    && apt-get clean


RUN /usr/bin/python3 -m venv /.venv
RUN /.venv/bin/pip3 install psycopg2-binary==2.9.10 asyncpg sqlalchemy alembic

ENV VIRTUAL_ENV=/.venv
ENV PATH=/.venv/bin:$PATH


# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command to run PostgreSQL
CMD ["postgres"]
