from mhd_ws.domain.exceptions.base import NotFoundError, RequestError


class AsyncTaskError(Exception): ...


class AsyncTaskNotFoundError(AsyncTaskError, NotFoundError, RequestError): ...


class AsyncTaskStartFailure(AsyncTaskError): ...


class AsyncTaskCheckStatusFailure(AsyncTaskError): ...


class AsyncTaskRemoteFailure(AsyncTaskError): ...


class AsyncTaskAlreadyStartedError(AsyncTaskError, RequestError): ...


class AsyncTaskNotReadyError(AsyncTaskError, RequestError): ...


class AsyncTaskResultExistsError(AsyncTaskError, RequestError): ...
