class AimError(Exception): ...


class IdentityError(AimError): ...


class AuthenticationError(AimError): ...


class AuthenticationRequiredError(AuthenticationError): ...


class AuthorizationError(AimError): ...
