from mhd_ws.domain.entities.search.index_search_spec import Target, ValueType
from mhd_ws.domain.entities.search.registries.models import (
    AllowedOperators,
    FieldDef,
    FieldRegistry,
)

FIELD_REGISTRY = FieldRegistry(
    fields=[
        # --- join / identity ---
        FieldDef(
            field_id="dataset_id",
            field_key="dataset_id",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
                allowed_comparators=["EQ"],
            ),
            description="Dataset identifier (canonical join key)",
        ),
        # --- dataset text-ish ---
        FieldDef(
            field_id="dataset_title",
            field_key="dataset.title",
            target=Target.DATASET,
            value_type=ValueType.TEXT,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["AUTO", "PHRASE", "EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Study/dataset title",
        ),
        FieldDef(
            field_id="dataset_description",
            field_key="dataset.description",
            target=Target.DATASET,
            value_type=ValueType.TEXT,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["AUTO", "PHRASE"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Study/dataset description",
        ),
        FieldDef(
            field_id="dataset_search_text",
            field_key="dataset.search_text",
            target=Target.DATASET,
            value_type=ValueType.TEXT,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["AUTO", "PHRASE"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Flattened dataset search_text",
        ),
        # --- dataset facets (keyword) ---
        FieldDef(
            field_id="facet_organisms",
            field_key="dataset.facets.organisms",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted organisms",
            facet_key="organisms",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_diseases",
            field_key="dataset.facets.diseases",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted diseases",
            facet_key="diseases",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_sample_types",
            field_key="dataset.facets.sample_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted sample types",
            facet_key="sample_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_tissues",
            field_key="dataset.facets.tissues",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted tissues",
            facet_key="tissues",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_characteristic_types",
            field_key="dataset.facets.characteristic_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted characteristic types",
            facet_key="characteristic_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_omics_types",
            field_key="dataset.facets.omics_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted omics types",
            facet_key="omics_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_measurement_types",
            field_key="dataset.facets.measurement_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted measurement types",
            facet_key="measurement_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_assay_types",
            field_key="dataset.facets.assay_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted assay types",
            facet_key="assay_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_technology_types",
            field_key="dataset.facets.technology_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted technology types",
            facet_key="technology_types",
            facet_type="value",
        ),
        # --- dataset numeric counts ---
        FieldDef(
            field_id="samples_count",
            field_key="dataset.samples.count",
            target=Target.DATASET,
            value_type=ValueType.NUMBER,
            ops=AllowedOperators(
                allow_terms=False,
                allow_comparators=True,
                allowed_match_modes=[],
                allowed_intra_combiners=[],
                allowed_comparators=["GT", "GTE", "LT", "LTE", "EQ"],
            ),
            description="Number of samples",
        ),
        FieldDef(
            field_id="assays_count",
            field_key="dataset.assays.count",
            target=Target.DATASET,
            value_type=ValueType.NUMBER,
            ops=AllowedOperators(
                allow_terms=False,
                allow_comparators=True,
                allowed_match_modes=[],
                allowed_intra_combiners=[],
                allowed_comparators=["GT", "GTE", "LT", "LTE", "EQ"],
            ),
            description="Number of assays",
        ),
        # --- dataset nested person search ---
        FieldDef(
            field_id="person_name",
            field_key="dataset.people.full_name",
            target=Target.DATASET,
            value_type=ValueType.TEXT,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["AUTO", "PHRASE", "EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="People.full_name (nested)",
        ),
        # --- dataset keyword filters ---
        FieldDef(
            field_id="dataset_profile",
            field_key="dataset.profile",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
            ),
            description="Dataset profile (e.g. legacy, ms)",
            facet_key="profile",
            facet_type="value",
        ),
        FieldDef(
            field_id="dataset_repository",
            field_key="dataset.repository.name",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
            ),
            description="Repository name (e.g. MetaboLights)",
            facet_key="repository",
            facet_type="value",
        ),
        FieldDef(
            field_id="dataset_license",
            field_key="dataset.study.license",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
            ),
            description="Dataset license URL",
        ),
        FieldDef(
            field_id="dataset_mhd_identifier",
            field_key="dataset.study.mhd_identifier",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
            ),
            description="MHD canonical identifier (ms profile)",
        ),
        # --- dataset facets (ms additions) ---
        FieldDef(
            field_id="facet_protocol_types",
            field_key="dataset.facets.protocol_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted protocol types",
            facet_key="protocol_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_parameter_types",
            field_key="dataset.facets.parameter_types",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted parameter types",
            facet_key="parameter_types",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_parameter_values",
            field_key="dataset.facets.parameter_values",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Faceted parameter values",
            facet_key="parameter_values",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_parameter_kv",
            field_key="dataset.facets.parameter_kv",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description='Parameter type+value pairs as "type_name::value" (e.g. "Ion mode::positive")',
            facet_key="parameter_kv",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_descriptors",
            field_key="dataset.descriptors.name",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR", "AND"],
            ),
            description="Descriptor names (nested, facet scoped to keyword relationships)",
            facet_key="descriptors",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_ms_instruments",
            field_key="dataset.ms_instruments.name",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR", "AND"],
            ),
            description="Mass spectrometry instrument names (nested)",
            facet_key="ms_instruments",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_chromatography_instruments",
            field_key="dataset.chromatography_instruments.name",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR", "AND"],
            ),
            description="Chromatography instrument names (nested)",
            facet_key="chromatography_instruments",
            facet_type="value",
        ),
        FieldDef(
            field_id="facet_other_instruments",
            field_key="dataset.other_instruments.name",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR", "AND"],
            ),
            description="Other instrument names (nested)",
            facet_key="other_instruments",
            facet_type="value",
        ),
        # --- dataset numeric counts (ms additions) ---
        FieldDef(
            field_id="sample_runs_count",
            field_key="dataset.counts.sample_runs",
            target=Target.DATASET,
            value_type=ValueType.NUMBER,
            ops=AllowedOperators(
                allow_terms=False,
                allow_comparators=True,
                allowed_match_modes=[],
                allowed_intra_combiners=[],
                allowed_comparators=["GT", "GTE", "LT", "LTE", "EQ"],
            ),
            description="Number of sample runs (ms profile)",
        ),
        FieldDef(
            field_id="subjects_count",
            field_key="dataset.counts.subjects",
            target=Target.DATASET,
            value_type=ValueType.NUMBER,
            ops=AllowedOperators(
                allow_terms=False,
                allow_comparators=True,
                allowed_match_modes=[],
                allowed_intra_combiners=[],
                allowed_comparators=["GT", "GTE", "LT", "LTE", "EQ"],
            ),
            description="Number of subjects (ms profile)",
        ),
        # --- dataset date range facets (display-only, not filterable via clauses) ---
        FieldDef(
            field_id="submission_date",
            field_key="dataset.dates.submission",
            target=Target.DATASET,
            value_type=ValueType.DATE,
            ops=AllowedOperators(
                allow_terms=False,
                allow_comparators=False,
                allowed_match_modes=[],
                allowed_intra_combiners=[],
            ),
            description="Submission date (range facet only)",
            facet_key="submission_date",
            facet_type="range",
        ),
        FieldDef(
            field_id="public_release_date",
            field_key="dataset.dates.public_release",
            target=Target.DATASET,
            value_type=ValueType.DATE,
            ops=AllowedOperators(
                allow_terms=False,
                allow_comparators=True,
                allowed_match_modes=[],
                allowed_intra_combiners=[],
                allowed_comparators=["GT", "GTE", "LT", "LTE", "EQ"],
            ),
            description="Public release date",
            facet_key="public_release_date",
            facet_type="date_histogram",
        ),
        # --- dataset nested publication/person search ---
        FieldDef(
            field_id="publication_doi",
            field_key="dataset.publications.doi",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
            ),
            description="Publications.doi (nested)",
        ),
        FieldDef(
            field_id="person_orcid",
            field_key="dataset.people.orcid",
            target=Target.DATASET,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["OR"],
            ),
            description="People.orcid (nested)",
        ),
        # --- metabolite fields ---
        FieldDef(
            field_id="metabolite_name",
            field_key="metabolite.name",
            target=Target.METABOLITE,
            value_type=ValueType.TEXT,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["AUTO", "PHRASE", "EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Metabolite name",
        ),
        FieldDef(
            field_id="metabolite_accession",
            field_key="metabolite.accession",
            target=Target.METABOLITE,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Metabolite accession",
        ),
        # --- metabolite identifiers (nested) ---
        FieldDef(
            field_id="metabolite_identifier_accession",
            field_key="metabolite.identifiers.accession",
            target=Target.METABOLITE,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Metabolite identifiers.accession (nested)",
        ),
        FieldDef(
            field_id="metabolite_identifier_name",
            field_key="metabolite.identifiers.name",
            target=Target.METABOLITE,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Metabolite identifiers.name (nested)",
        ),
        FieldDef(
            field_id="metabolite_identifier_source",
            field_key="metabolite.identifiers.source",
            target=Target.METABOLITE,
            value_type=ValueType.KEYWORD,
            ops=AllowedOperators(
                allow_terms=True,
                allow_comparators=False,
                allowed_match_modes=["EXACT"],
                allowed_intra_combiners=["AND", "OR"],
            ),
            description="Metabolite identifiers.source (nested)",
        ),
    ]
)
